// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZD8TXhaE6lr29R4no573qydMzUAL597Y',
    appId: '1:465121616495:web:f5575743436a14e786e39a',
    messagingSenderId: '465121616495',
    projectId: 'tssr-79f4a',
    authDomain: 'tssr-79f4a.firebaseapp.com',
    storageBucket: 'tssr-79f4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOu3aLaX0FXNYCXZmgv8nfjcuinOwUOOY',
    appId: '1:465121616495:android:8a4e7b4f81a3421186e39a',
    messagingSenderId: '465121616495',
    projectId: 'tssr-79f4a',
    storageBucket: 'tssr-79f4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOVsGTVdnjUjt7mtW7lB7RoDDE6YTaN0',
    appId: '1:465121616495:ios:f2c1b5471a245cb386e39a',
    messagingSenderId: '465121616495',
    projectId: 'tssr-79f4a',
    storageBucket: 'tssr-79f4a.appspot.com',
    iosClientId: '465121616495-d8mkicd5ae3f29l17jcdohjurc2e3dcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tssrCtrl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOVsGTVdnjUjt7mtW7lB7RoDDE6YTaN0',
    appId: '1:465121616495:ios:f2c1b5471a245cb386e39a',
    messagingSenderId: '465121616495',
    projectId: 'tssr-79f4a',
    storageBucket: 'tssr-79f4a.appspot.com',
    iosClientId: '465121616495-d8mkicd5ae3f29l17jcdohjurc2e3dcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tssrCtrl',
  );
}
